import { buildCompositeAdmissibleSegmentsForSolution } from '../../../composite/admissibleGeometry.js'
import { buildDrawableCompositeSegments } from '../../../../geometry/compositeCurveGeometry.js'
import { normalizeSegment } from '../../../composite/admissible/primitives.js'
import { buildStopGeometry } from '../../../composite/admissible/stopping.js'
import {
  filterCompositeBranchesSharingRarefactionAnchors,
  keepDrawableSegment,
  orientSegmentBySpeed,
  restrictCompositeFromRarefactionAnchor,
  splitSegmentBySpeed,
} from '../../../composite/admissible/restriction.js'
import { buildCompositeSegments, buildCompositeSegmentsFromRarefaction } from '../../../waves/index.js'
import { makeRarefactionParam, makeCompositeLevelFunction } from '../../../composite/bifoliation/parametrization.js'
import { COMPOSITE } from '../../../../config/numerics.js'
import { compositeSpeedOrientationDiagnostics } from './compositeOrientation.js'
import { RAREFACTION, clampResolutionSamples } from '../../../../config/numerics.js'
import { waveSpeed } from '../../../surfaceImplicit/index.js'
import {
  coordsOf,
  pointObjectFromCoords,
  hasUsableSegments,
  sonicValue,
  sonicBranchMatches,
  sonicRightBranch,
  sonicRightBranchIndicatorValue,
  refineSonicCrossing,
} from '../pipelineShared.js'
import {
  normalizedDistance3,
  scaledSegmentLength,
  trimSegmentsToPoint,
} from './commonGeometry.js'

export function buildSolutionCompositeSegments(anchorPoint, params, view, resolution, direction, sonicTarget, inflectionBranch, admissibleOrientation, stopFixedState = null) {
  if (!anchorPoint) return []
  return buildCompositeAdmissibleSegmentsForSolution({
    fixedState: anchorPoint,
    stopFixedState,
    params,
    view,
    resolution,
    direction,
    sonicTarget,
    inflectionBranch,
    admissibleOrientation,
  })
}

export function buildGlobalCompositeIntersectionSegments(anchorPoint, params, view, resolution, direction, sonicTarget, inflectionBranch) {
  if (!anchorPoint) return []
  const samples = clampResolutionSamples(
    (resolution ?? 40) * RAREFACTION.SAMPLES_PER_RESOLUTION,
    RAREFACTION.MIN_SAMPLES,
    RAREFACTION.MAX_SAMPLES,
  )
  const data = buildCompositeSegments(
    anchorPoint,
    params,
    view,
    samples,
    resolution,
    inflectionBranch,
    direction,
    sonicTarget,
  )
  return buildDrawableCompositeSegments(data?.segments ?? [])
    .filter((segment) => keepDrawableSegment(segment, view))
}


/**
 * Builds the complete composite intersection generated by an already-built
 * rarefaction curve.  This is the nonlocal analogue of
 * buildGlobalCompositeIntersectionSegments: no admissibility, monotonicity or
 * connectivity filter is applied here.  The desired arc is selected later by
 * anchoring the global curve at the refined rarefaction endpoint J.
 */
export function buildGlobalCompositeIntersectionFromRarefactionCurve(
  rarefactionCurveSegments,
  curveBasePoint,
  params,
  view,
  direction,
  sonicTarget,
  inflectionBranch,
) {
  if (!hasUsableSegments(rarefactionCurveSegments)) return []
  const raw = []
  for (const segment of rarefactionCurveSegments ?? []) {
    if (!Array.isArray(segment) || segment.length < 2) continue
    const result = buildCompositeSegmentsFromRarefaction(
      segment,
      params,
      view,
      view,
      inflectionBranch,
      direction,
      sonicTarget,
      pointObjectFromCoords(curveBasePoint),
    )
    for (const item of result?.segments ?? []) raw.push(item)
  }
  return buildDrawableCompositeSegments(raw)
    .filter((segment) => keepDrawableSegment(segment, view))
}



function evaluateCompositeLeafPoint(level, u, eta, params, sonicTarget) {
  const w = level.wFromEta(eta)
  const obj = level.saturation.evaluate(u, w)
  const point = obj?.point
  if (!point) return null
  const value = sonicValue(point, params, sonicTarget)
  if (!Number.isFinite(value)) return null
  return { ...obj, point, value, eta, w }
}

function orientedHugoniotEtaSign(level, u, eta0, params, sonicTarget, etaMin, etaMax) {
  const base = evaluateCompositeLeafPoint(level, u, eta0, params, sonicTarget)
  const baseSpeed = base?.point ? waveSpeed(base.point.t, base.point.z, params) : Number.NaN
  const span = Math.max(1e-8, etaMax - etaMin)
  const delta = Math.max(1e-6, 1e-4 * span)
  const candidates = []
  for (const sign of [1, -1]) {
    const eta = Math.max(etaMin, Math.min(etaMax, eta0 + sign * delta))
    if (Math.abs(eta - eta0) < 1e-14) continue
    const sample = evaluateCompositeLeafPoint(level, u, eta, params, sonicTarget)
    if (!sample?.point) continue
    const speed = waveSpeed(sample.point.t, sample.point.z, params)
    if (!Number.isFinite(speed)) continue
    candidates.push({ sign, speed, deltaSpeed: Number.isFinite(baseSpeed) ? speed - baseSpeed : 0 })
  }
  if (!candidates.length) return 1
  // H_- is followed in its intrinsic orientation ds < 0.  This determines
  // which side of eta=z(generator) is traversed; it is not an orientation
  // filter on the composite curve.
  candidates.sort((a, b) => a.deltaSpeed - b.deltaSpeed)
  return candidates[0].sign
}

function refineFirstLeafSonicIntersection(level, u, leftEta, rightEta, leftValue, params, sonicTarget, sonicBranch) {
  let a = leftEta
  let b = rightEta
  let fa = leftValue
  let best = null
  for (let k = 0; k < 72; k += 1) {
    const mid = 0.5 * (a + b)
    const sample = evaluateCompositeLeafPoint(level, u, mid, params, sonicTarget)
    if (!sample) break
    best = sample
    const scale = Math.max(1, Math.abs(fa), Math.abs(sample.value))
    if (Math.abs(sample.value) <= 1e-10 * scale || Math.abs(b - a) <= 1e-12) break
    if (fa * sample.value <= 0) {
      b = mid
    } else {
      a = mid
      fa = sample.value
    }
  }
  if (!best?.point) return null
  return sonicBranchMatches(best.point, params, sonicTarget, sonicBranch) ? best : null
}

function firstSonicIntersectionAlongEtaDirection({
  level,
  u,
  eta0,
  etaEnd,
  atGenerator,
  params,
  sonicTarget,
  sonicBranch,
  etaSamples,
}) {
  const count = Math.max(80, etaSamples ?? 260)
  let previous = atGenerator
  let previousEta = eta0

  for (let i = 1; i <= count; i += 1) {
    const alpha = i / count
    const eta = eta0 + alpha * (etaEnd - eta0)
    const current = evaluateCompositeLeafPoint(level, u, eta, params, sonicTarget)
    if (!current) {
      previous = null
      previousEta = eta
      continue
    }
    const scale = Math.max(1, Math.abs(current.value), Math.abs(previous?.value ?? 0))
    if (Math.abs(current.value) <= 1e-9 * scale
      && sonicBranchMatches(current.point, params, sonicTarget, sonicBranch)) {
      return current
    }
    if (previous && previous.value * current.value <= 0) {
      const root = refineFirstLeafSonicIntersection(
        level,
        u,
        previousEta,
        eta,
        previous.value,
        params,
        sonicTarget,
        sonicBranch,
      )
      if (root) return root
    }
    previous = current
    previousEta = eta
  }
  return null
}

function firstSonicIntersectionOnOrientedHugoniotLeaf({
  level,
  u,
  generator,
  params,
  sonicTarget,
  sonicBranch,
  etaMin,
  etaMax,
  etaSamples,
}) {
  const eta0 = generator?.z
  if (!Number.isFinite(eta0)) return null
  const atGenerator = evaluateCompositeLeafPoint(level, u, eta0, params, sonicTarget)
  if (atGenerator?.point) {
    const scale = Math.max(1, Math.abs(atGenerator.value))
    if (Math.abs(atGenerator.value) <= 1e-9 * scale
      && sonicBranchMatches(atGenerator.point, params, sonicTarget, sonicBranch)) {
      return atGenerator
    }
  }

  // Follow the intrinsic H_- side first. Near the characteristic plane the
  // numerical speed comparison used to infer that side may be ambiguous, so
  // the opposite eta side is retained as a fallback instead of returning an
  // empty composite curve.
  const preferredSign = orientedHugoniotEtaSign(
    level,
    u,
    eta0,
    params,
    sonicTarget,
    etaMin,
    etaMax,
  )
  for (const sign of [preferredSign, -preferredSign]) {
    const etaEnd = sign > 0 ? etaMax : etaMin
    if (Math.abs(etaEnd - eta0) < 1e-14) continue
    const hit = firstSonicIntersectionAlongEtaDirection({
      level,
      u,
      eta0,
      etaEnd,
      atGenerator,
      params,
      sonicTarget,
      sonicBranch,
      etaSamples,
    })
    if (hit) return hit
  }
  return null
}

/**
 * Construct K directly as the ordered sequence of first intersections
 *
 *   H_-(R_nloc(u)) cap S^-
 *
 * while following each H_- leaf from its characteristic generator in the
 * intrinsic H_- direction.  The rarefaction arc is expected to be ordered
 * from P2 to J; we traverse u from J back to P2, so the returned composite
 * already starts at J and has no alternative side that must be selected.
 */
export function buildFirstIntersectionCompositeFromRarefactionArc(
  rarefactionArcSegments,
  params,
  view,
  direction,
  sonicTarget = 'left',
  sonicBranch = 'slow',
  { uSamples = 180, etaSamples = 300 } = {},
) {
  if (!hasUsableSegments(rarefactionArcSegments)) return []
  const output = []
  for (const segment of rarefactionArcSegments ?? []) {
    const rareParam = makeRarefactionParam(segment, view)
    if (!rareParam) continue
    const etaSpan = Math.max(1e-9, view.zMax - view.zMin)
    const marginFactor = COMPOSITE.HUGONIOT_SATURATION_ETA_MARGIN_FACTOR
      ?? COMPOSITE.ETA_MARGIN_FACTOR
      ?? 0
    const etaMargin = Math.max(0, marginFactor) * etaSpan
    const etaMin = view.zMin - etaMargin
    const etaMax = view.zMax + etaMargin
    const level = makeCompositeLevelFunction(
      rareParam,
      params,
      direction,
      sonicTarget,
      etaMin,
      etaMax,
      sonicBranch,
    )
    const points = []
    let consecutiveMisses = 0
    const count = Math.max(48, uSamples, (segment?.length ?? 2) * 2)
    const maxConsecutiveMisses = Math.max(8, Math.ceil(count * 0.06))
    for (let i = 0; i <= count; i += 1) {
      const u = 1 - i / count
      const generator = rareParam.interpolate(u)
      const hit = firstSonicIntersectionOnOrientedHugoniotLeaf({
        level,
        u,
        generator,
        params,
        sonicTarget,
        sonicBranch,
        etaMin,
        etaMax,
        etaSamples,
      })
      if (!hit?.point) {
        consecutiveMisses += 1
        if (points.length >= 2 && consecutiveMisses > maxConsecutiveMisses) break
        continue
      }
      consecutiveMisses = 0
      const point = {
        ...hit.point,
        compositeU: u,
        compositeW: hit.w,
        generatorPoint: generator,
        coords: [...hit.point.coords],
      }
      if (!points.length || normalizedDistance3(points[points.length - 1], point, view) > 1e-10) {
        points.push(point)
      }
    }
    if (points.length >= 2) output.push(points)
  }
  return buildDrawableCompositeSegments(output)
    .filter((segment) => keepDrawableSegment(segment, view))
}

export function normalizedCompositeTortuosity(segment, view) {
  if (!Array.isArray(segment) || segment.length < 2) return Number.POSITIVE_INFINITY
  const length = scaledSegmentLength(segment, view)
  const chord = normalizedDistance3(segment[0], segment[segment.length - 1], view)
  if (!Number.isFinite(length) || length <= 0) return Number.POSITIVE_INFINITY
  if (!Number.isFinite(chord) || chord <= 1e-8) return Number.POSITIVE_INFINITY
  return length / chord
}

export function pointRecords(segment, params) {
  return (segment ?? [])
    .map((point) => {
      const coords = coordsOf(point)
      if (!coords) return null
      const speed = waveSpeed(coords[0], coords[2], params)
      return coords.every(Number.isFinite) && Number.isFinite(speed)
        ? {
          coords: [...coords],
          speed,
          compositeU: Number.isFinite(point?.compositeU) ? point.compositeU : null,
          compositeW: Number.isFinite(point?.compositeW) ? point.compositeW : null,
        }
        : null
    })
    .filter(Boolean)
}

export function nearestRecordIndex(records, anchorCoords, view) {
  let index = -1
  let distance = Number.POSITIVE_INFINITY
  for (let i = 0; i < records.length; i += 1) {
    const d = normalizedDistance3(records[i].coords, anchorCoords, view)
    if (d < distance) {
      distance = d
      index = i
    }
  }
  return { index, distance }
}

export function insertAnchorAtRecordIndex(records, anchorCoords, anchorIndex, params) {
  if (!records?.length || anchorIndex < 0) return []
  const anchorSpeed = waveSpeed(anchorCoords[0], anchorCoords[2], params)
  if (!Number.isFinite(anchorSpeed)) return records
  const out = records.map((record) => ({
    coords: [...record.coords],
    speed: record.speed,
    compositeU: record.compositeU,
    compositeW: record.compositeW,
  }))
  out[anchorIndex] = {
    coords: [...anchorCoords],
    speed: anchorSpeed,
    compositeU: out[anchorIndex]?.compositeU ?? null,
    compositeW: out[anchorIndex]?.compositeW ?? null,
  }
  return out
}

export function compositeCandidateDiagnostics(segment, anchorCoords, view) {
  const length = scaledSegmentLength(segment, view)
  const anchorDistance = normalizedDistance3(segment?.[0], anchorCoords, view)
  const tortuosity = normalizedCompositeTortuosity(segment, view)
  return { length, anchorDistance, tortuosity }
}

export function directionalCompositeDrift(records) {
  const withU = (records ?? []).filter((record) => Number.isFinite(record.compositeU))
  if (withU.length < 2) return 0
  const first = withU[0].compositeU
  const last = withU[withU.length - 1].compositeU
  if (!Number.isFinite(first) || !Number.isFinite(last)) return 0
  return last - first
}

export function splitConnectedSubarcsFromAnchor(records, anchorIndex) {
  if (!records?.length || anchorIndex < 0) return []
  const anchor = records[anchorIndex]
  if (!anchor?.coords || !Number.isFinite(anchor.speed)) return []

  const out = []
  for (const step of [1, -1]) {
    const sideRecords = [{ ...anchor, coords: [...anchor.coords] }]
    for (let index = anchorIndex + step; index >= 0 && index < records.length; index += step) {
      const next = records[index]
      if (!next?.coords || !Number.isFinite(next.speed)) break
      sideRecords.push({ ...next, coords: [...next.coords] })
    }
    if (sideRecords.length >= 2) {
      out.push({
        segment: sideRecords.map((record) => record.coords),
        records: sideRecords,
        step,
      })
    }
  }
  return out
}

export function extractOrientedCompositeArcFromFullCurve(
  rawSegments,
  anchorPoint,
  params,
  view,
  orientation,
  { maxAnchorDistance = 0.075, maxTortuosity = 14.0, minLength = 0.001 } = {},
) {
  const anchorCoords = coordsOf(anchorPoint)
  if (!anchorCoords || !hasUsableSegments(rawSegments)) return []

  const candidates = []
  for (const rawSegment of rawSegments ?? []) {
    const baseRecords = pointRecords(rawSegment, params)
    if (baseRecords.length < 2) continue
    const nearest = nearestRecordIndex(baseRecords, anchorCoords, view)
    if (nearest.index < 0 || nearest.distance > maxAnchorDistance) continue
    const records = insertAnchorAtRecordIndex(baseRecords, anchorCoords, nearest.index, params)

    const subarcs = splitConnectedSubarcsFromAnchor(records, nearest.index)
    for (const { segment, records: sideRecords, step } of subarcs) {
      const diagnostics = compositeCandidateDiagnostics(segment, anchorCoords, view)
      if (!Number.isFinite(diagnostics.length) || diagnostics.length <= minLength) continue
      // Very large tortuosity usually means a component switched branches, but
      // near J the admissible component can be moderately curved.  Penalize it
      // in ranking instead of discarding aggressively.
      const tortuosityPenalty = Number.isFinite(diagnostics.tortuosity)
        ? Math.max(0, diagnostics.tortuosity - maxTortuosity)
        : 100
      const drift = directionalCompositeDrift(sideRecords)
      const speedOrientation = compositeSpeedOrientationDiagnostics(sideRecords, orientation)
      candidates.push({
        segment,
        step,
        anchorDistance: nearest.distance,
        tortuosityPenalty,
        driftMagnitude: Math.abs(drift),
        ...speedOrientation,
        ...diagnostics,
      })
    }
  }

  if (!candidates.length) return []

  candidates.sort((a, b) => {
    // 1. The requested wave-speed orientation determines the admissible side
    // leaving the inflection.  This is a net endpoint test, not the removed
    // pointwise monotonicity filter, so small marching-squares oscillations do
    // not discard an otherwise valid connected arc.
    if (a.orientationMatches !== b.orientationMatches) {
      return a.orientationMatches ? -1 : 1
    }
    if (a.orientationMatches && b.orientationMatches
      && Math.abs(a.orientationStrength - b.orientationStrength) > 1e-10) {
      return b.orientationStrength - a.orientationStrength
    }
    // 2. Prefer components that actually contain the inflection anchor, but do
    // not over-penalize tiny marching-square misalignment near J.
    const anchorBinA = Math.floor(a.anchorDistance / 0.01)
    const anchorBinB = Math.floor(b.anchorDistance / 0.01)
    if (anchorBinA !== anchorBinB) return anchorBinA - anchorBinB
    // 3. Prefer a real component ordered by the rarefaction parameter, avoiding
    // nearly-zero u-drift chords that look like short straight artifacts.
    if (Math.abs(a.driftMagnitude - b.driftMagnitude) > 1e-6) return b.driftMagnitude - a.driftMagnitude
    // 4. Keep the longer connected side; the Hugoniot stop event trims it afterwards.
    if (Math.abs(a.length - b.length) > 1e-6) return b.length - a.length
    // 5. Finally prefer lower branch-switching/tortuosity penalty.
    if (Math.abs(a.tortuosityPenalty - b.tortuosityPenalty) > 1e-6) return a.tortuosityPenalty - b.tortuosityPenalty
    return a.anchorDistance - b.anchorDistance
  })

  return [candidates[0].segment]
}


function sideReferenceFromInflectionToRarefactionStart(inflectionPoint, rarefactionStartPoint, view) {
  const origin = coordsOf(inflectionPoint)
  const target = coordsOf(rarefactionStartPoint)
  if (!origin || !target) return null
  const tScale = Math.max(1e-6, Math.abs((view?.tMax ?? 1) - (view?.tMin ?? 0)))
  const zScale = Math.max(1e-6, Math.abs((view?.zMax ?? 1) - (view?.zMin ?? 0)))
  const targetVector = [
    (target[0] - origin[0]) / tScale,
    (target[2] - origin[2]) / zScale,
  ]
  return Math.hypot(targetVector[0], targetVector[1]) > 1e-7
    ? { origin, targetVector }
    : null
}

function buildNonlocalCompositeWithLocalRestriction({
  rawSegments,
  compositeAnchorPoints = null,
  inflectionPoint,
  rarefactionStartPoint,
  params,
  view,
  resolution,
  direction,
  admissibleOrientation,
  stopFixedState,
}) {
  const anchor = pointObjectFromCoords(inflectionPoint)
  const rarefactionStart = pointObjectFromCoords(rarefactionStartPoint) ?? anchor
  if (!anchor || !hasUsableSegments(rawSegments)) return []

  const normalizedRaw = (rawSegments ?? [])
    .map(normalizeSegment)
    .filter((segment) => segment.length >= 2)
  if (!normalizedRaw.length) return []

  // This deliberately mirrors buildCompositeAdmissibleSegmentsForSolution:
  // 1) keep only the components of Sat_{H_-}(R_nloc)∩S_- that pass through J;
  // 2) choose the admissible side starting at J using pointwise speed monotonicity;
  // 3) stop on H_-(U_L) / double sonic using the same stop geometry;
  // 4) only then convert to drawable segments.
  const compositeAnchors = (Array.isArray(compositeAnchorPoints) && compositeAnchorPoints.length)
    ? compositeAnchorPoints.map(pointObjectFromCoords).filter(Boolean)
    : []
  const branchTolerance = Math.max(0.025, 0.10 / Math.max(1, resolution))
  const branchSegments = filterCompositeBranchesSharingRarefactionAnchors(
    normalizedRaw,
    anchor,
    compositeAnchors,
    view,
    {
      branchTolerance,
      anchorTolerance: Math.max(0.030, 0.12 / Math.max(1, resolution)),
      fallbackToBranchPoint: true,
    },
  )
  const stopGeometry = buildStopGeometry({
    fixedState: rarefactionStart,
    stopFixedState,
    params,
    view,
    resolution,
    direction,
  })
  const sideReference = sideReferenceFromInflectionToRarefactionStart(anchor, rarefactionStart, view)
  const restrictionAnchors = compositeAnchors.length ? compositeAnchors : [anchor]
  const anchored = restrictCompositeFromRarefactionAnchor(
    branchSegments,
    restrictionAnchors,
    params,
    view,
    admissibleOrientation,
    stopGeometry,
    sideReference,
  )
  const source = anchored ?? branchSegments
  const oriented = source
    .flatMap((segment) => anchored ? [segment] : splitSegmentBySpeed(segment, params, admissibleOrientation))
    .map((segment) => anchored ? segment : orientSegmentBySpeed(segment, params, admissibleOrientation))

  return buildDrawableCompositeSegments(oriented)
    .filter((segment) => keepDrawableSegment(segment, view))
}

export function buildCompositeFromSpecifiedRarefactionCurve(
  rarefactionCurveSegments,
  inflectionPoint,
  params,
  view,
  resolution,
  direction,
  sonicTarget,
  inflectionBranch,
  admissibleOrientation,
  stopFixedState = null,
  _sideReferenceSegments = null,
  curveBasePoint = null,
) {
  const anchor = pointObjectFromCoords(inflectionPoint)
  const curveBase = pointObjectFromCoords(curveBasePoint) ?? anchor
  if (!anchor || !curveBase || !hasUsableSegments(rarefactionCurveSegments)) return []

  const raw = []
  const compositeAnchorPoints = []
  for (const segment of rarefactionCurveSegments ?? []) {
    if (!Array.isArray(segment) || segment.length < 2) continue
    const result = buildCompositeSegmentsFromRarefaction(
      segment,
      params,
      view,
      view,
      inflectionBranch,
      direction,
      sonicTarget,
      curveBase,
    )
    for (const item of result?.segments ?? []) raw.push(item)
    for (const item of result?.sonicAnchorPoints ?? (result?.sonicAnchorPoint ? [result.sonicAnchorPoint] : [])) {
      if (item) compositeAnchorPoints.push(item)
    }
  }

  if (!raw.length) return []

  // Return only the same local-style restriction used by K_loc.  The previous
  // fallback could select a different component of Sat_H(R_nloc) cap S when the
  // branch-through-inflection test was weak, which made K_nloc disagree with
  // the local composite construction.
  return buildNonlocalCompositeWithLocalRestriction({
    rawSegments: raw,
    compositeAnchorPoints,
    inflectionPoint: anchor,
    rarefactionStartPoint: curveBase,
    params,
    view,
    resolution,
    direction,
    admissibleOrientation,
    stopFixedState,
  })
}



export function firstSonicIntersectionOnSegments(
  segments,
  params,
  sonicTarget,
  sonicBranch = 'any',
  anchorPoint = null,
  view = null,
) {
  const anchor = pointObjectFromCoords(anchorPoint)
  const candidates = []

  const robustRightBranch = (crossing, a, b) => {
    const direct = sonicRightBranch(crossing, params)
    if (direct !== 'neutral' && direct !== 'unknown') return direct
    const samples = [a, crossing, b]
      .map((point) => sonicRightBranchIndicatorValue(point, params))
      .filter(Number.isFinite)
    if (!samples.length) return direct
    const scale = Math.max(1, ...samples.map((value) => Math.abs(value)))
    const tol = 1e-9 * scale
    const negative = samples.filter((value) => value < -tol)
    const positive = samples.filter((value) => value > tol)
    if (negative.length && !positive.length) return 'slow'
    if (positive.length && !negative.length) return 'fast'
    const average = samples.reduce((sum, value) => sum + value, 0) / samples.length
    if (average < -tol) return 'slow'
    if (average > tol) return 'fast'
    return direct
  }

  for (const sourceSegment of segments ?? []) {
    let points = (sourceSegment ?? []).map(pointObjectFromCoords).filter(Boolean)
    if (points.length < 2) continue

    // Always traverse each polyline from the endpoint closest to the physical
    // start of the Hugoniot arc.  Array order is not a geometric ordering.
    let startDistance = 0
    if (anchor && view) {
      const d0 = normalizedDistance3(points[0], anchor, view)
      const d1 = normalizedDistance3(points[points.length - 1], anchor, view)
      if (d1 < d0) points = [...points].reverse()
      startDistance = Math.min(d0, d1)
    }

    let travelled = startDistance
    for (let i = 0; i < points.length - 1; i += 1) {
      const a = points[i]
      const b = points[i + 1]
      const edgeLength = view ? normalizedDistance3(a, b, view) : 1
      const fa = sonicValue(a, params, sonicTarget)
      const fb = sonicValue(b, params, sonicTarget)
      if (!Number.isFinite(fa) || !Number.isFinite(fb)) {
        travelled += edgeLength
        continue
      }

      const addCandidate = (crossing, alpha) => {
        if (!crossing) return
        const branch = sonicTarget === 'right'
          ? robustRightBranch(crossing, a, b)
          : null
        if (sonicBranch !== 'any' && branch !== sonicBranch) return
        candidates.push({
          point: crossing,
          branch,
          arcLength: travelled + Math.max(0, Math.min(1, alpha)) * edgeLength,
        })
      }

      if (Math.abs(fa) < 1e-9) addCandidate(a, 0)
      if (fa * fb <= 0 || Math.abs(fb) < 1e-9) {
        const crossing = refineSonicCrossing(a, b, params, sonicTarget) ?? b
        const denom = Math.abs(fa) + Math.abs(fb)
        const alpha = denom > 1e-14 ? Math.abs(fa) / denom : 1
        addCandidate(crossing, alpha)
      }
      travelled += edgeLength
    }
  }

  candidates.sort((a, b) => a.arcLength - b.arcLength)
  return candidates[0] ?? null
}

export function trimSegmentsToFirstSonic(
  segments,
  params,
  view,
  sonicTarget,
  sonicBranch = 'any',
  anchorPoint = null,
) {
  const hit = firstSonicIntersectionOnSegments(
    segments,
    params,
    sonicTarget,
    sonicBranch,
    anchorPoint,
    view,
  )
  if (!hit?.point) return { segments: segments ?? [], sonicPoint: null, sonicBranch: null }
  return {
    segments: trimSegmentsToPoint(segments, hit.point, view, { preserveTarget: true }),
    sonicPoint: hit.point,
    sonicBranch: hit.branch ?? (sonicTarget === 'right' ? sonicRightBranch(hit.point, params) : null),
  }
}

