export const defaultSolutionVisibility = {
  slow: {
    hugoniotLocal: true,
    hugoniotNonlocal: true,
    auxiliaryHPlus: true,
    rarefactionLocal: true,
    rarefactionNonlocal: true,
    composite: true,
    compositeLocal: true,
    compositeNonlocal: true,
    involvedRarefactionCurve: false,
    involvedCompositeCurve: false,
    satInvolvedRarefactionCurve: false,
    satHugoniotLocal: false,
    satHugoniotNonlocal: false,
    satRarefactionLocal: false,
    satRarefactionNonlocal: false,
    satComposite: false,
    chosenHPlusIntersection: false,
    chosenHMinusRarefaction: false,
  },
  fast: {
    hugoniotLocal: false,
    hugoniotNonlocal: false,
    rarefactionLocal: false,
    rarefactionNonlocal: false,
    composite: false,
    compositeLocal: false,
    compositeNonlocal: false,
    involvedRarefactionCurve: false,
    involvedCompositeCurve: false,
  },
  reflected: {
    hugoniotLocal: false,
    hugoniotNonlocal: false,
    rarefactionLocal: false,
    rarefactionNonlocal: false,
    composite: false,
    compositeLocal: false,
    compositeNonlocal: false,
    involvedRarefactionCurve: false,
    involvedCompositeCurve: false,
  },
}

export const defaultCurveVisibility = {
  slow: { hugoniotMinus: true, hugoniotPlus: true, rarefaction: true },
  fast: { hugoniotMinus: true, hugoniotPlus: true, rarefaction: true },
}
