import React from 'react'

import OverlayPanel from '../../components/panel/OverlayPanel'

export default function WaveOverlayPanel({
  state,
  calculationView,
  actions,
  visibility,
  selection,
  showHysteresis,
  canEnableInspectionMode,
  setInspectionModeEnabled,
  canEnableSolutionMode,
  setSolutionModeEnabled,
  onExportSnapshot,
  onCreateInspectionProbe,
  onMoveInspectionProbe,
}) {
  return (
    <OverlayPanel
      params={state.params}
      setParams={actions.setParams}
      view={state.view}
      calculationView={calculationView}
      setView={actions.setView}
      resetParams={actions.resetParams}
      resetView={actions.resetView}
      yScale={state.yScale}
      setYScale={actions.setYScale}
      tScale={state.tScale}
      setTScale={actions.setTScale}
      zScale={state.zScale}
      setZScale={actions.setZScale}
      resolution={state.resolution}
      setResolution={actions.setResolution}
      opacity={state.opacity}
      setOpacity={actions.setOpacity}
      showAxes={state.showAxes}
      setShowAxes={actions.setShowAxes}
      showCharacteristic={state.showCharacteristic}
      setShowCharacteristic={actions.setShowCharacteristic}
      showSonicRight={visibility.showSonicRight}
      setShowSonicRight={actions.setShowSonicRight}
      showSonicLeft={visibility.showSonicLeft}
      setShowSonicLeft={actions.setShowSonicLeft}
      showHopfPlus={visibility.showHopfPlus}
      setShowHopfPlus={actions.setShowHopfPlus}
      showHopfMinus={visibility.showHopfMinus}
      setShowHopfMinus={actions.setShowHopfMinus}
      showHysteresisSelfIntersection={visibility.showHysteresisSelfIntersection}
      setShowHysteresisSelfIntersection={actions.setShowHysteresisSelfIntersection}
      showSaturatedPlus={visibility.showSaturatedPlus}
      setShowSaturatedPlus={actions.setShowSaturatedPlus}
      showDoubleSonicMinusProjection={state.showDoubleSonicMinusProjection}
      showHysteresisSelfIntersectionMinusProjection={state.showHysteresisSelfIntersectionMinusProjection}
      setShowDoubleSonicMinusProjection={actions.setShowDoubleSonicMinusProjection}
      setShowHysteresisSelfIntersectionMinusProjection={actions.setShowHysteresisSelfIntersectionMinusProjection}
      showDoubleSonicPlusProjection={state.showDoubleSonicPlusProjection}
      showHysteresisSelfIntersectionPlusProjection={state.showHysteresisSelfIntersectionPlusProjection}
      setShowDoubleSonicPlusProjection={actions.setShowDoubleSonicPlusProjection}
      setShowHysteresisSelfIntersectionPlusProjection={actions.setShowHysteresisSelfIntersectionPlusProjection}
      showExtensionMinusMinusProjection={state.showExtensionMinusMinusProjection}
      showExtensionPlusMinusProjection={state.showExtensionPlusMinusProjection}
      setShowExtensionMinusMinusProjection={actions.setShowExtensionMinusMinusProjection}
      setShowExtensionPlusMinusProjection={actions.setShowExtensionPlusMinusProjection}
      showExtensionMinusPlusProjection={state.showExtensionMinusPlusProjection}
      showExtensionPlusPlusProjection={state.showExtensionPlusPlusProjection}
      setShowExtensionMinusPlusProjection={actions.setShowExtensionMinusPlusProjection}
      setShowExtensionPlusPlusProjection={actions.setShowExtensionPlusPlusProjection}
      showInflectionMinusProjection={state.showInflectionMinusProjection}
      setShowInflectionMinusProjection={actions.setShowInflectionMinusProjection}
      showInflectionPlusProjection={state.showInflectionPlusProjection}
      setShowInflectionPlusProjection={actions.setShowInflectionPlusProjection}
      showHysPlusMinusProjection={state.showHysPlusMinusProjection}
      showCoincidenceMinusProjection={state.showCoincidenceMinusProjection}
      showRarefactionSlowMinusProjection={state.showRarefactionSlowMinusProjection}
      showRarefactionFastMinusProjection={state.showRarefactionFastMinusProjection}
      showCompositeSlowMinusProjection={state.showCompositeSlowMinusProjection}
      showCompositeFastMinusProjection={state.showCompositeFastMinusProjection}
      showCoincidencePlusProjection={state.showCoincidencePlusProjection}
      showRarefactionSlowPlusProjection={state.showRarefactionSlowPlusProjection}
      showRarefactionFastPlusProjection={state.showRarefactionFastPlusProjection}
      showCompositeSlowPlusProjection={state.showCompositeSlowPlusProjection}
      showCompositeFastPlusProjection={state.showCompositeFastPlusProjection}
      showHysMinusMinusProjection={state.showHysMinusMinusProjection}
      setShowHysPlusMinusProjection={actions.setShowHysPlusMinusProjection}
      setShowCoincidenceMinusProjection={actions.setShowCoincidenceMinusProjection}
      setShowRarefactionSlowMinusProjection={actions.setShowRarefactionSlowMinusProjection}
      setShowRarefactionFastMinusProjection={actions.setShowRarefactionFastMinusProjection}
      setShowCompositeSlowMinusProjection={actions.setShowCompositeSlowMinusProjection}
      setShowCompositeFastMinusProjection={actions.setShowCompositeFastMinusProjection}
      setShowCoincidencePlusProjection={actions.setShowCoincidencePlusProjection}
      setShowRarefactionSlowPlusProjection={actions.setShowRarefactionSlowPlusProjection}
      setShowRarefactionFastPlusProjection={actions.setShowRarefactionFastPlusProjection}
      setShowCompositeSlowPlusProjection={actions.setShowCompositeSlowPlusProjection}
      setShowCompositeFastPlusProjection={actions.setShowCompositeFastPlusProjection}
      setShowHysMinusMinusProjection={actions.setShowHysMinusMinusProjection}
      showHysPlusPlusProjection={state.showHysPlusPlusProjection}
      showHugoniotMinusPlusProjection={state.showHugoniotMinusPlusProjection}
      showHugoniotPlusPlusProjection={state.showHugoniotPlusPlusProjection}
      showHugoniotMinusMinusProjection={state.showHugoniotMinusMinusProjection}
      showHugoniotPlusMinusProjection={state.showHugoniotPlusMinusProjection}
      showHysMinusPlusProjection={state.showHysMinusPlusProjection}
      setShowHysPlusPlusProjection={actions.setShowHysPlusPlusProjection}
      setShowHugoniotMinusPlusProjection={actions.setShowHugoniotMinusPlusProjection}
      setShowHugoniotPlusPlusProjection={actions.setShowHugoniotPlusPlusProjection}
      setShowHugoniotMinusMinusProjection={actions.setShowHugoniotMinusMinusProjection}
      setShowHugoniotPlusMinusProjection={actions.setShowHugoniotPlusMinusProjection}
      setShowHysMinusPlusProjection={actions.setShowHysMinusPlusProjection}
      showSaturated={visibility.showSaturated}
      setShowSaturated={actions.setShowSaturated}
      showSaturatedCoincidence={visibility.showSaturatedCoincidence}
      setShowSaturatedCoincidence={actions.setShowSaturatedCoincidence}
      showSaturatedCoincidencePlus={visibility.showSaturatedCoincidencePlus}
      setShowSaturatedCoincidencePlus={actions.setShowSaturatedCoincidencePlus}
      showExtensionCoincidenceMinus={visibility.showExtensionCoincidenceMinus}
      setShowExtensionCoincidenceMinus={actions.setShowExtensionCoincidenceMinus}
      showExtensionCoincidencePlus={visibility.showExtensionCoincidencePlus}
      setShowExtensionCoincidencePlus={actions.setShowExtensionCoincidencePlus}
      showRarefactionSlow={visibility.showRarefactionSlow}
      setShowRarefactionSlow={actions.setShowRarefactionSlow}
      showRarefactionFast={visibility.showRarefactionFast}
      setShowRarefactionFast={actions.setShowRarefactionFast}
      showCompositeSlow={visibility.showCompositeSlow}
      setShowCompositeSlow={actions.setShowCompositeSlow}
      showCompositeFast={visibility.showCompositeFast}
      setShowCompositeFast={actions.setShowCompositeFast}
      showCompositeSaturatedSlow={visibility.showCompositeSaturatedSlow}
      setShowCompositeSaturatedSlow={actions.setShowCompositeSaturatedSlow}
      showCompositeSaturatedFast={visibility.showCompositeSaturatedFast}
      setShowCompositeSaturatedFast={actions.setShowCompositeSaturatedFast}
      showHugoniotMinus={visibility.showHugoniotMinus}
      setShowHugoniotMinus={actions.setShowHugoniotMinus}
      showHugoniotPlus={visibility.showHugoniotPlus}
      setShowHugoniotPlus={actions.setShowHugoniotPlus}
      showHysteresis={showHysteresis}
      setShowHysteresis={actions.setShowHysteresis}
      showHysteresisLeft={visibility.showHysteresisLeft}
      setShowHysteresisLeft={actions.setShowHysteresisLeft}
      showHysteresisRight={visibility.showHysteresisRight}
      setShowHysteresisRight={actions.setShowHysteresisRight}
      showCoincidence={visibility.showCoincidence}
      setShowCoincidence={actions.setShowCoincidence}
      showBifurcationRight={visibility.showBifurcationRight}
      setShowBifurcationRight={actions.setShowBifurcationRight}
      showInflectionSlow={visibility.showInflectionSlow}
      setShowInflectionSlow={actions.setShowInflectionSlow}
      showInflectionFast={visibility.showInflectionFast}
      setShowInflectionFast={actions.setShowInflectionFast}
      showDoubleSonic={visibility.showDoubleSonic}
      setShowDoubleSonic={actions.setShowDoubleSonic}
      selectedEntries={selection.displayedSelectedEntries}
      activeBranch={state.activeBranch}
      selectedCharacteristicPoint={selection.selectedCharacteristicPoint}
      selectedClickSource={selection.selectedClickSource}
      selectedState={selection.selectedState}
      hugoniotIntersections={selection.hugoniotIntersections}
      inspectedCurvePoint={state.inspectedCurvePoint}
      hoveredInspectionPoint={state.hoveredInspectionPoint}
      clearSelectedState={selection.clearSelection}
      activeView={state.activeView}
      setActiveView={actions.setActiveView}
      autoRotate3D={state.autoRotate3D}
      setAutoRotate3D={actions.setAutoRotate3D}
      inspectionModeEnabled={state.inspectionModeEnabled}
      setInspectionModeEnabled={setInspectionModeEnabled}
      canEnableInspectionMode={canEnableInspectionMode}
      solutionModeEnabled={state.solutionModeEnabled}
      setSolutionModeEnabled={setSolutionModeEnabled}
      canEnableSolutionMode={canEnableSolutionMode}
      inspectionProbesByBranch={state.inspectionProbesByBranch}
      onCreateInspectionProbe={onCreateInspectionProbe}
      onMoveInspectionProbe={onMoveInspectionProbe}
      inspectionCurveVisibility={state.inspectionCurveVisibility}
      setInspectionCurveVisibility={actions.setInspectionCurveVisibility}
      solutionCurveVisibility={state.solutionCurveVisibility}
      setSolutionCurveVisibility={actions.setSolutionCurveVisibility}
      solutionDiagnostics={state.solutionDiagnostics}
      onSelectCharacteristicPoint={selection.onMoveSelectedPoint}
      onExportSnapshot={onExportSnapshot}
    />
  )
}







